### ISSUE TITLE
Getting all nested childrens (recursive)

### ISSUE THREAD

**Issue by frantisek-heca** [vanilophp/category#2]
Please, I haven't tried this package, but I am mostly interested if children method will return all nested categories, preferably in a tree view (nested array)?

If not, how would you get it? For building menus.

**Comment by fulopattila122** [comment]
I would start from the root level taxons and then iterate through the children:

```php
foreach ($taxonomy->rootLevelTaxons() as $root) {
    foreach ($root->children() as $child) {
        $child->children();//...and so on
    }
}
```
