### ISSUE TITLE
Rename Taxon to Category

### ISSUE THREAD

**Issue by jonathan-martz** [vanilophp/category#3]
Hey, 
i was looking for a list of categorys.
I tried the same like i did with Product and was looking for a category model, but i could not find the class, because i was looking for Category Model.

I few minutes later i found the taxonmy class and i finde the taxonmy class naming not that perfect.

The accentual name for the class is Category, tax is something total different for me.

Could you rename it ?

**Comment by fulopattila122** [comment]
> Could you rename it?

Sorry but not at all.

- Imagine it would break the system for all the users of the framework
- Taxonomy is absolutely the right term here: _Taxonomy (general) is the practice and science of classification of things or concepts_, see: https://en.wikipedia.org/wiki/Taxonomy
- A category is only one of the possible classification options (think of brands, offers, etc)
- Taxonomy has nothing to do with taxes
- Many systems use the terms Taxonomy and Taxon:
    - https://guides.spreecommerce.org/user/products/taxonomies_and_taxons.html
    - https://www.drupal.org/docs/user_guide/en/structure-taxonomy.html
    - https://www.bigcommerce.com/blog/product-taxonomy
