### ISSUE TITLE
Use nested set model for taxonomies

### ISSUE THREAD

**Issue by huiyang** [vanilophp/category#4]
I like vanilo very much as it is so clean and modular, but except that its taxonomies/categories is not using nested set model 😭
Is it possible for vanilo category to implement nested set model? by using one either lazychaser/laravel-nestedset or rinvex/categories package?

Thanks for your consideraion.

**Comment by fulopattila122** [comment]
What is the functionality you're exactly looking for?

**Comment by huiyang** [comment]
Just about performance concern, as i have 3 -4 levels of categories of products for some of my project.
Ya, it still workable to get it recursively, so might not really a priority right now?

**Comment by fulopattila122** [comment]
As the functionality exists it's not our aim to switch to another implementation for the category module.

Nevertheless, if it's important for you, there are two options to have it implemented your way:

1. Omit the category module completely and replace it with your implementation. In this case, you have to [omit the framework and pull the individual modules](https://vanilo.io/docs/1.2/modules-vs-framework) you'd like to use into your application.
2. Use the category module, but [replace the models](https://vanilo.io/how-to/use-custom-models-in-your-application) with your implementation. It's not necessary to inherit from the [base models](https://vanilo.io/docs/1.2/models), so you can start from scratch. The only requirements are that the class a) should be an eloquent model, b) implement the `Taxonomy` and `Taxon` interfaces.

See the rest in the linked Documentation. If you have questions feel free to ask in this thread. I'd also like to hear about your experience if it succeeds.

**Comment by huiyang** [comment]
OK, let me try when my schedule is less packed, appreaciated for your reply!
